// <auto-generated />
using System;
using Assessment.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assessment.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assessment.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Author");

                    b.HasIndex("Name");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Assessment.Domain.Entities.BookReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpectedDateOfReturn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CustomerId");

                    b.ToTable("BookReservations");
                });

            modelBuilder.Entity("Assessment.Domain.Entities.BookReservationNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsNotified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BookReservationNotifications");
                });

            modelBuilder.Entity("Assessment.Domain.Entities.Permission", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            IsDeleted = false,
                            Name = "AddBook"
                        },
                        new
                        {
                            Id = (short)2,
                            IsDeleted = false,
                            Name = "GetBook"
                        },
                        new
                        {
                            Id = (short)3,
                            IsDeleted = false,
                            Name = "SearchBook"
                        },
                        new
                        {
                            Id = (short)4,
                            IsDeleted = false,
                            Name = "BookReturn"
                        },
                        new
                        {
                            Id = (short)5,
                            IsDeleted = false,
                            Name = "ReservationNotification"
                        },
                        new
                        {
                            Id = (short)6,
                            IsDeleted = false,
                            Name = "BookCollection"
                        },
                        new
                        {
                            Id = (short)7,
                            IsDeleted = false,
                            Name = "ReserveBook"
                        });
                });

            modelBuilder.Entity("Assessment.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(8029),
                            IsDeleted = false,
                            LastModified = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(8030),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(8032),
                            IsDeleted = false,
                            LastModified = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(8032),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Assessment.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<short>("PermissionId")
                        .HasColumnType("smallint");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("RolePermission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(7685),
                            IsDeleted = false,
                            LastModified = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(7685),
                            PermissionId = (short)1,
                            RoleId = (short)1
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(7688),
                            IsDeleted = false,
                            LastModified = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(7688),
                            PermissionId = (short)2,
                            RoleId = (short)1
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(7690),
                            IsDeleted = false,
                            LastModified = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(7690),
                            PermissionId = (short)3,
                            RoleId = (short)1
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(7691),
                            IsDeleted = false,
                            LastModified = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(7691),
                            PermissionId = (short)4,
                            RoleId = (short)1
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(7695),
                            IsDeleted = false,
                            LastModified = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(7695),
                            PermissionId = (short)5,
                            RoleId = (short)1
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(7698),
                            IsDeleted = false,
                            LastModified = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(7698),
                            PermissionId = (short)6,
                            RoleId = (short)1
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(7699),
                            IsDeleted = false,
                            LastModified = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(7700),
                            PermissionId = (short)2,
                            RoleId = (short)2
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(7701),
                            IsDeleted = false,
                            LastModified = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(7701),
                            PermissionId = (short)3,
                            RoleId = (short)2
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(7702),
                            IsDeleted = false,
                            LastModified = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(7703),
                            PermissionId = (short)7,
                            RoleId = (short)2
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(7705),
                            IsDeleted = false,
                            LastModified = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(7705),
                            PermissionId = (short)5,
                            RoleId = (short)2
                        });
                });

            modelBuilder.Entity("Assessment.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerType")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoginFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerType");

                    b.HasIndex("Email");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Assessment.Domain.Entities.UserInRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserInRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(8919),
                            IsDeleted = false,
                            LastModified = new DateTime(2024, 10, 4, 4, 38, 19, 814, DateTimeKind.Utc).AddTicks(8919),
                            RoleId = (short)1,
                            UserId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
